import { completePtSessionAction, createPtPackageAction } from "@/app/actions";
import { PtBookingForm } from "@/components/training/pt-booking-form";
import { requireAppContext } from "@/lib/app-context";
import { formatDateTime } from "@/lib/format";

export default async function TrainingPage() {
  const ctx = await requireAppContext();
  const [sessionsRes,membersRes,trainersRes,packagesRes] = await Promise.all([
    ctx.supabase.from("pt_sessions").select("id,starts_at,ends_at,status,member_id,trainer_user_id,pt_package_id,members(first_name,last_name)").eq("organization_id",ctx.organization.id).order("starts_at",{ascending:false}).limit(100),
    ctx.supabase.from("members").select("id,first_name,last_name").eq("organization_id",ctx.organization.id).is("archived_at",null).order("first_name").limit(500),
    ctx.supabase.from("organization_members").select("user_id,role,profiles(full_name)").eq("organization_id",ctx.organization.id).eq("is_active",true).in("role",["trainer","owner","admin","manager"]),
    ctx.supabase.from("pt_packages").select("id,member_id,sessions_purchased,sessions_remaining,expires_on").eq("organization_id",ctx.organization.id).gt("sessions_remaining",0),
  ]);
  return <section className="mx-auto max-w-7xl space-y-6"><div><p className="text-sm text-[#7a7f89]">Personal training</p><h1 className="mt-1 text-3xl font-semibold tracking-tight">Training</h1></div><div className="grid gap-6 xl:grid-cols-2"><section className="rounded-2xl border border-[#e4e6ea] bg-white p-5"><h2 className="font-semibold">Sell PT package</h2><form action={createPtPackageAction} className="mt-4 grid gap-3 sm:grid-cols-2"><select name="member_id" required className="rounded-lg border border-[#dfe2e7] px-3 py-2"><option value="">Member…</option>{(membersRes.data??[]).map((m:any)=><option key={m.id} value={m.id}>{m.first_name} {m.last_name}</option>)}</select><select name="trainer_user_id" className="rounded-lg border border-[#dfe2e7] px-3 py-2"><option value="">Any trainer</option>{(trainersRes.data??[]).map((t:any)=><option key={t.user_id} value={t.user_id}>{t.profiles?.full_name || t.role}</option>)}</select><input name="sessions" required type="number" min="1" placeholder="Sessions" className="rounded-lg border border-[#dfe2e7] px-3 py-2"/><input name="expires_on" type="date" className="rounded-lg border border-[#dfe2e7] px-3 py-2"/><button className="sm:col-span-2 rounded-lg bg-[#111318] px-4 py-2 text-sm font-semibold text-white">Create package</button></form></section><section className="rounded-2xl border border-[#e4e6ea] bg-white p-5"><h2 className="font-semibold">Book PT session</h2><PtBookingForm members={(membersRes.data??[]) as any} trainers={(trainersRes.data??[]) as any} packages={(packagesRes.data??[]) as any} timezone={ctx.organization.timezone} /></section></div>
    <section className="rounded-2xl border border-[#e4e6ea] bg-white"><div className="border-b border-[#eceef1] p-5"><h2 className="font-semibold">Session ledger</h2></div><div className="divide-y divide-[#f0f1f3]">{(sessionsRes.data??[]).map((s:any)=><div key={s.id} className="flex flex-wrap items-center justify-between gap-4 p-4"><div><p className="font-medium">{s.members?.first_name} {s.members?.last_name}</p><p className="mt-1 text-xs text-[#7a7f89]">{formatDateTime(s.starts_at,ctx.organization.timezone)} → {formatDateTime(s.ends_at,ctx.organization.timezone)}</p></div><div className="flex items-center gap-3"><span className="rounded-full bg-[#f0f2f4] px-2.5 py-1 text-xs font-semibold capitalize">{s.status.replace('_',' ')}</span>{s.status==='scheduled'&&<form action={completePtSessionAction}><input type="hidden" name="session_id" value={s.id}/><button className="rounded-lg border border-[#111318] px-3 py-1.5 text-xs font-semibold">Complete</button></form>}</div></div>)}</div></section></section>;
}
