import { notFound } from "next/navigation";
import { addMemberNoteAction, archiveMemberAction, assignAccessCredentialAction, enrollMembershipAction, freezeMembershipAction, recordPaymentAction, revokeAccessCredentialAction, updateMemberAction } from "@/app/actions";
import { PhotoUploader } from "@/components/members/photo-uploader";
import { requireAppContext } from "@/lib/app-context";
import { durationBetween, formatDate, formatDateTime, formatMoney, memberDisplayNumber } from "@/lib/format";
import { dateInTimeZone } from "@/lib/time";

export default async function MemberDetailPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const ctx = await requireAppContext();
  const [memberRes, plansRes, membershipsRes, paymentsRes, attendanceRes, notesRes, credentialsRes] = await Promise.all([
    ctx.supabase.from("members").select("*").eq("organization_id", ctx.organization.id).eq("id", id).maybeSingle(),
    ctx.supabase.from("membership_plans").select("id,name,price_minor,currency,duration_days,included_visits,billing_type").eq("organization_id", ctx.organization.id).eq("is_active", true).order("name"),
    ctx.supabase.from("memberships").select("id,status,starts_on,ends_on,visits_remaining,price_minor,currency,plan_id,membership_plans(name),membership_freezes(id,starts_on,ends_on,reason)").eq("organization_id", ctx.organization.id).eq("member_id", id).order("created_at", { ascending: false }),
    ctx.supabase.from("payments").select("id,receipt_number,amount_minor,currency,payment_method,status,paid_at,membership_id").eq("organization_id", ctx.organization.id).eq("member_id", id).order("paid_at", { ascending: false }).limit(100),
    ctx.supabase.from("attendance_sessions").select("id,checked_in_at,checked_out_at,check_in_method,forced_closed").eq("organization_id", ctx.organization.id).eq("member_id", id).order("checked_in_at", { ascending: false }).limit(30),
    ctx.supabase.from("member_notes").select("id,note,created_at").eq("organization_id", ctx.organization.id).eq("member_id", id).order("created_at", { ascending: false }).limit(20),
    ctx.supabase.from("access_credentials").select("id,credential_type,last_four,label,is_active,issued_at").eq("organization_id", ctx.organization.id).eq("member_id", id).order("issued_at", { ascending: false }),
  ]);
  const member: any = memberRes.data;
  if (!member) notFound();
  const memberships: any[] = membershipsRes.data ?? [];
  const today = dateInTimeZone(new Date(), ctx.organization.timezone);
  const active = memberships.find((m) => m.status === "active" && m.starts_on <= today && (!m.ends_on || m.ends_on >= today));
  let photoUrl: string | null = null;
  if (member.photo_path) {
    const { data } = await ctx.supabase.storage.from("member-private").createSignedUrl(member.photo_path, 3600);
    photoUrl = data?.signedUrl ?? null;
  }
  const paidTotals = new Map<string, number>();
  for (const payment of (paymentsRes.data ?? []).filter((p: any) => p.status === "paid")) {
    paidTotals.set(payment.currency, (paidTotals.get(payment.currency) ?? 0) + Number(payment.amount_minor));
  }
  const paidTotalDisplay = paidTotals.size ? [...paidTotals].map(([currency, amount]) => formatMoney(amount, currency)).join(" · ") : formatMoney(0, ctx.organization.base_currency);

  return <section className="mx-auto max-w-7xl space-y-6">
    <div className="rounded-2xl border border-[#e4e6ea] bg-white p-5 lg:p-6"><div className="flex flex-wrap items-start justify-between gap-5"><div className="flex items-center gap-4"><div className="h-16 w-16 overflow-hidden rounded-2xl bg-[#eceef1]">{photoUrl ? <img src={photoUrl} alt="Member" className="h-full w-full object-cover" /> : <div className="grid h-full w-full place-items-center text-lg font-bold">{member.first_name[0]}{member.last_name[0]}</div>}</div><div><p className="text-sm text-[#7a7f89]">{memberDisplayNumber(member.member_number)}</p><h1 className="text-3xl font-semibold tracking-tight">{member.first_name} {member.last_name}</h1><p className="mt-1 text-sm text-[#707680]">{member.phone || "No phone"} · {member.email || "No email"}</p><div className="mt-2"><PhotoUploader organizationId={ctx.organization.id} memberId={id} /></div></div></div><div className="rounded-xl bg-[#f5f6f7] px-4 py-3 text-sm"><p className="font-semibold">{active?.membership_plans?.name ?? "No active membership"}</p><p className="mt-1 text-[#777d86]">{active ? `Expires ${formatDate(active.ends_on)}${active.visits_remaining != null ? ` · ${active.visits_remaining} visits left` : ""}` : "Assign a plan below"}</p></div></div></div>

    <div className="grid gap-6 xl:grid-cols-[1.2fr_.8fr]">
      <div className="space-y-6">
        <section className="rounded-2xl border border-[#e4e6ea] bg-white p-5"><h2 className="font-semibold">Profile</h2><form action={updateMemberAction} className="mt-4 grid gap-4 md:grid-cols-2"><input type="hidden" name="member_id" value={id} /><label className="text-sm">First name<input name="first_name" required defaultValue={member.first_name} className="mt-1 w-full rounded-lg border border-[#dfe2e7] px-3 py-2" /></label><label className="text-sm">Last name<input name="last_name" required defaultValue={member.last_name} className="mt-1 w-full rounded-lg border border-[#dfe2e7] px-3 py-2" /></label><label className="text-sm">Phone<input name="phone" defaultValue={member.phone ?? ""} className="mt-1 w-full rounded-lg border border-[#dfe2e7] px-3 py-2" /></label><label className="text-sm">Email<input name="email" type="email" defaultValue={member.email ?? ""} className="mt-1 w-full rounded-lg border border-[#dfe2e7] px-3 py-2" /></label><label className="text-sm">Date of birth<input name="date_of_birth" type="date" defaultValue={member.date_of_birth ?? ""} className="mt-1 w-full rounded-lg border border-[#dfe2e7] px-3 py-2" /></label><label className="text-sm">Emergency contact<input name="emergency_contact_name" defaultValue={member.emergency_contact_name ?? ""} className="mt-1 w-full rounded-lg border border-[#dfe2e7] px-3 py-2" /></label><label className="text-sm">Emergency phone<input name="emergency_contact_phone" defaultValue={member.emergency_contact_phone ?? ""} className="mt-1 w-full rounded-lg border border-[#dfe2e7] px-3 py-2" /></label><div className="flex items-end"><button className="w-full rounded-lg bg-[#111318] px-4 py-2.5 text-sm font-semibold text-white">Save profile</button></div></form></section>

        <section className="rounded-2xl border border-[#e4e6ea] bg-white"><div className="border-b border-[#eceef1] p-5"><h2 className="font-semibold">Membership history</h2></div><div className="divide-y divide-[#f0f1f3]">{memberships.map((m: any) => { const linkedPaid=(paymentsRes.data??[]).filter((p:any)=>p.status==="paid"&&p.membership_id===m.id).reduce((sum:number,p:any)=>sum+Number(p.amount_minor),0); const balance=Math.max(0,Number(m.price_minor)-linkedPaid); const frozenNow=(m.membership_freezes??[]).some((f:any)=>f.starts_on<=today&&f.ends_on>=today); return <div key={m.id} className="p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="font-medium">{m.membership_plans?.name ?? "Membership"}</p><p className="mt-1 text-xs text-[#7a7f89]">{formatDate(m.starts_on)} → {formatDate(m.ends_on)}{m.visits_remaining != null ? ` · ${m.visits_remaining} visits remaining` : ""}</p><p className="mt-1 text-xs text-[#7a7f89]">Paid {formatMoney(linkedPaid,m.currency)} · Balance {formatMoney(balance,m.currency)}{frozenNow ? " · Frozen now" : ""}</p></div><span className="rounded-full bg-[#f0f2f4] px-2.5 py-1 text-xs font-semibold capitalize">{m.status}</span></div>{(m.membership_freezes??[]).length>0&&<div className="mt-3 space-y-1">{m.membership_freezes.map((f:any)=><p key={f.id} className="text-xs text-[#6f7580]">Freeze: {formatDate(f.starts_on)} → {formatDate(f.ends_on)}{f.reason?` · ${f.reason}`:""}</p>)}</div>}{m.status==="active"&&<details className="mt-3"><summary className="cursor-pointer text-xs font-semibold">Freeze / pause membership</summary><form action={freezeMembershipAction} className="mt-3 grid gap-2 sm:grid-cols-4"><input type="hidden" name="member_id" value={id}/><input type="hidden" name="membership_id" value={m.id}/><input name="starts_on" type="date" min={today} required className="rounded-lg border border-[#dfe2e7] px-2 py-1.5 text-xs"/><input name="ends_on" type="date" min={today} required className="rounded-lg border border-[#dfe2e7] px-2 py-1.5 text-xs"/><input name="reason" placeholder="Reason (optional)" className="rounded-lg border border-[#dfe2e7] px-2 py-1.5 text-xs"/><button className="rounded-lg border border-[#111318] px-2 py-1.5 text-xs font-semibold">Apply freeze</button></form></details>}</div>})}{memberships.length === 0 && <p className="p-5 text-sm text-[#7a7f89]">No memberships yet.</p>}</div></section>

        <section className="rounded-2xl border border-[#e4e6ea] bg-white"><div className="border-b border-[#eceef1] p-5"><h2 className="font-semibold">Attendance</h2></div><div className="divide-y divide-[#f0f1f3]">{(attendanceRes.data ?? []).map((a: any) => <div key={a.id} className="flex items-center justify-between gap-4 p-4 text-sm"><div><p className="font-medium">{formatDateTime(a.checked_in_at, ctx.organization.timezone)}</p><p className="text-xs text-[#7a7f89]">{a.check_in_method}{a.forced_closed ? " · auto/forced close" : ""}</p></div><div className="text-right"><p>{a.checked_out_at ? formatDateTime(a.checked_out_at, ctx.organization.timezone) : "Currently inside"}</p><p className="text-xs text-[#7a7f89]">{durationBetween(a.checked_in_at, a.checked_out_at)}</p></div></div>)}{!(attendanceRes.data?.length) && <p className="p-5 text-sm text-[#7a7f89]">No visits recorded.</p>}</div></section>
      </div>

      <div className="space-y-6">
        <section className="rounded-2xl border border-[#e4e6ea] bg-white p-5"><h2 className="font-semibold">Add / renew membership</h2><form action={enrollMembershipAction} className="mt-4 space-y-3"><input type="hidden" name="member_id" value={id} /><label className="block text-sm">Plan<select name="plan_id" required className="mt-1 w-full rounded-lg border border-[#dfe2e7] px-3 py-2.5"><option value="">Choose plan…</option>{(plansRes.data ?? []).map((p: any) => <option key={p.id} value={p.id}>{p.name} · {formatMoney(p.price_minor, p.currency)}</option>)}</select></label><label className="block text-sm">Start date<input name="starts_on" type="date" required defaultValue={new Date().toISOString().slice(0,10)} className="mt-1 w-full rounded-lg border border-[#dfe2e7] px-3 py-2.5" /></label><label className="block text-sm">Amount paid now<input name="amount_paid" inputMode="decimal" defaultValue="0" className="mt-1 w-full rounded-lg border border-[#dfe2e7] px-3 py-2.5" /></label><label className="block text-sm">Payment method<select name="payment_method" defaultValue="cash" className="mt-1 w-full rounded-lg border border-[#dfe2e7] px-3 py-2.5"><option value="cash">Cash</option><option value="card_terminal">Card terminal</option><option value="bank_transfer">Bank transfer</option><option value="whish">Whish</option><option value="omt">OMT</option><option value="other">Other</option></select></label><button className="w-full rounded-lg bg-[#111318] px-4 py-2.5 text-sm font-semibold text-white">Create membership</button></form></section>

        <section className="rounded-2xl border border-[#e4e6ea] bg-white p-5"><div className="flex items-center justify-between"><h2 className="font-semibold">Payments</h2><span className="text-sm text-[#6f7580]">Recorded: {paidTotalDisplay}</span></div><div className="mt-4 space-y-2">{(paymentsRes.data ?? []).slice(0,6).map((p: any) => <div key={p.id} className="flex items-center justify-between rounded-xl bg-[#f7f8f9] p-3 text-sm"><div><p className="font-medium"><a href={`/receipts/${p.id}`} className="underline decoration-[#c5c9cf] underline-offset-4">Receipt #{p.receipt_number}</a></p><p className="text-xs capitalize text-[#7a7f89]">{p.payment_method} · {p.status}</p></div><span className="font-semibold">{formatMoney(p.amount_minor,p.currency)}</span></div>)}</div><form action={recordPaymentAction} className="mt-4 grid gap-3"><input type="hidden" name="member_id" value={id} /><input type="hidden" name="currency" value={ctx.organization.base_currency} /><label className="text-sm">Apply to membership<select name="membership_id" className="mt-1 w-full rounded-lg border border-[#dfe2e7] px-3 py-2"><option value="">General payment</option>{memberships.map((m:any)=><option key={m.id} value={m.id}>{m.membership_plans?.name} · {formatDate(m.starts_on)}</option>)}</select></label><div className="grid grid-cols-2 gap-2"><input name="amount" required inputMode="decimal" placeholder="Amount" className="rounded-lg border border-[#dfe2e7] px-3 py-2" /><select name="payment_method" defaultValue="cash" className="rounded-lg border border-[#dfe2e7] px-3 py-2"><option value="cash">Cash</option><option value="card_terminal">Card</option><option value="bank_transfer">Transfer</option><option value="whish">Whish</option><option value="omt">OMT</option></select></div><button className="rounded-lg border border-[#111318] px-4 py-2 text-sm font-semibold">Record payment</button></form></section>

        <section className="rounded-2xl border border-[#e4e6ea] bg-white p-5"><h2 className="font-semibold">Access cards & fobs</h2><div className="mt-3 space-y-2">{(credentialsRes.data ?? []).map((c:any)=><div key={c.id} className="rounded-xl bg-[#f7f8f9] p-3 text-sm"><p className="font-medium capitalize">{c.label || c.credential_type} •••• {c.last_four || ""}</p><div className="mt-1 flex items-center justify-between gap-3"><p className="text-xs text-[#7a7f89]">{c.is_active ? "Active" : "Revoked"} · issued {formatDateTime(c.issued_at, ctx.organization.timezone)}</p>{c.is_active && <form action={revokeAccessCredentialAction}><input type="hidden" name="member_id" value={id}/><input type="hidden" name="credential_id" value={c.id}/><button className="text-xs font-semibold text-red-700">Revoke</button></form>}</div></div>)}</div><form action={assignAccessCredentialAction} className="mt-4 space-y-3"><input type="hidden" name="member_id" value={id} /><select name="credential_type" defaultValue="rfid" className="w-full rounded-lg border border-[#dfe2e7] px-3 py-2"><option value="rfid">RFID</option><option value="nfc">NFC</option><option value="magstripe">Magstripe</option><option value="barcode">Barcode</option><option value="qr">QR</option></select><input name="raw_token" required autoComplete="off" placeholder="Swipe/tap card here" className="w-full rounded-lg border border-[#dfe2e7] px-3 py-2" /><input name="label" placeholder="Label (optional)" className="w-full rounded-lg border border-[#dfe2e7] px-3 py-2" /><button className="w-full rounded-lg border border-[#111318] px-4 py-2 text-sm font-semibold">Assign credential</button></form></section>

        <section className="rounded-2xl border border-[#e4e6ea] bg-white p-5"><h2 className="font-semibold">Notes</h2><form action={addMemberNoteAction} className="mt-3"><input type="hidden" name="member_id" value={id} /><textarea name="note" required rows={3} placeholder="Operational note…" className="w-full rounded-lg border border-[#dfe2e7] px-3 py-2 text-sm" /><button className="mt-2 rounded-lg border border-[#111318] px-3 py-2 text-sm font-semibold">Add note</button></form><div className="mt-4 space-y-2">{(notesRes.data ?? []).map((n:any)=><div key={n.id} className="rounded-xl bg-[#f7f8f9] p-3 text-sm"><p>{n.note}</p><p className="mt-1 text-xs text-[#7a7f89]">{formatDateTime(n.created_at, ctx.organization.timezone)}</p></div>)}</div></section>

        {(["owner","admin","manager"] as string[]).includes(ctx.role) && <section className="rounded-2xl border border-red-100 bg-white p-5"><h2 className="font-semibold">Archive member</h2><p className="mt-1 text-sm text-[#7a7f89]">The profile disappears from active operations but financial and attendance history is retained.</p><form action={archiveMemberAction} className="mt-3"><input type="hidden" name="member_id" value={id} /><button className="rounded-lg border border-red-200 px-3 py-2 text-sm font-semibold text-red-700">Archive</button></form></section>}
      </div>
    </div>
  </section>;
}
