import { recordPaymentAction, voidPaymentAction } from "@/app/actions";
import { AccessDenied } from "@/components/access-denied";
import { requireAppContext } from "@/lib/app-context";
import { formatDateTime, formatMoney } from "@/lib/format";
import { ROLE_GROUPS, roleAllowed } from "@/lib/roles";

export default async function PaymentsPage() {
  const ctx = await requireAppContext();
  if (!roleAllowed(ctx.role, ROLE_GROUPS.financial)) return <AccessDenied area="payments" />;
  const canVoid=roleAllowed(ctx.role, ROLE_GROUPS.paymentVoiders);
  const [paymentsRes, membersRes] = await Promise.all([
    ctx.supabase.from("payments").select("id,receipt_number,amount_minor,currency,payment_method,status,paid_at,member_id,members(first_name,last_name)").eq("organization_id",ctx.organization.id).order("paid_at",{ascending:false}).limit(150),
    ctx.supabase.from("members").select("id,first_name,last_name").eq("organization_id",ctx.organization.id).is("archived_at",null).order("first_name").limit(500),
  ]);
  if(paymentsRes.error) throw new Error(paymentsRes.error.message);
  if(membersRes.error) throw new Error(membersRes.error.message);
  const paid=(paymentsRes.data??[]).filter((p:any)=>p.status==="paid");
  const totals=new Map<string,number>();paid.forEach((p:any)=>totals.set(p.currency,(totals.get(p.currency)??0)+Number(p.amount_minor)));
  return <section className="mx-auto max-w-7xl space-y-6"><div><p className="text-sm text-[#7a7f89]">Financial ledger</p><h1 className="mt-1 text-3xl font-semibold tracking-tight">Payments</h1></div><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><div className="rounded-2xl border border-[#e4e6ea] bg-white p-5"><p className="text-sm text-[#6f7580]">Recorded paid</p><p className="mt-3 text-2xl font-semibold">{totals.size?[...totals].map(([c,v])=>formatMoney(v,c)).join(" · "):formatMoney(0,ctx.organization.base_currency)}</p></div><div className="rounded-2xl border border-[#e4e6ea] bg-white p-5"><p className="text-sm text-[#6f7580]">Transactions</p><p className="mt-3 text-2xl font-semibold">{paymentsRes.data?.length??0}</p></div></div>
    <section className="rounded-2xl border border-[#e4e6ea] bg-white p-5"><h2 className="font-semibold">Record payment</h2><form action={recordPaymentAction} className="mt-4 grid gap-3 md:grid-cols-3 xl:grid-cols-6"><select name="member_id" required className="rounded-lg border border-[#dfe2e7] px-3 py-2"><option value="">Member…</option>{(membersRes.data??[]).map((m:any)=><option key={m.id} value={m.id}>{m.first_name} {m.last_name}</option>)}</select><input name="amount" required inputMode="decimal" placeholder="Amount" className="rounded-lg border border-[#dfe2e7] px-3 py-2"/><select name="currency" defaultValue={ctx.organization.base_currency} className="rounded-lg border border-[#dfe2e7] px-3 py-2"><option>USD</option><option>EUR</option><option>LBP</option></select><select name="payment_method" defaultValue="cash" className="rounded-lg border border-[#dfe2e7] px-3 py-2"><option value="cash">Cash</option><option value="card_terminal">Card terminal</option><option value="bank_transfer">Transfer</option><option value="whish">Whish</option><option value="omt">OMT</option><option value="other">Other</option></select><input name="external_reference" placeholder="Reference (optional)" className="rounded-lg border border-[#dfe2e7] px-3 py-2"/><button data-feedback="Recording payment…" className="rounded-lg bg-[#111318] px-4 py-2 text-sm font-semibold text-white">Record</button></form></section>
    <section className="rounded-2xl border border-[#e4e6ea] bg-white"><div className="overflow-x-auto"><table className="w-full min-w-[850px] text-left text-sm"><thead className="bg-[#fafafa] text-xs uppercase text-[#8a9099]"><tr><th className="px-5 py-3">Receipt</th><th>Member</th><th>Amount</th><th>Method</th><th>Status</th><th>Date</th><th></th></tr></thead><tbody>{(paymentsRes.data??[]).map((p:any)=><tr key={p.id} className="border-t border-[#f0f1f3]"><td className="px-5 py-4 font-medium"><a href={`/receipts/${p.id}`} className="underline decoration-[#c5c9cf] underline-offset-4">#{p.receipt_number}</a></td><td>{p.members?.first_name} {p.members?.last_name}</td><td className="font-semibold">{formatMoney(p.amount_minor,p.currency)}</td><td className="capitalize">{String(p.payment_method).replaceAll("_"," ")}</td><td className="capitalize">{p.status}</td><td>{formatDateTime(p.paid_at,ctx.organization.timezone)}</td><td className="pr-5 text-right">{p.status==="paid"&&canVoid&&<form action={voidPaymentAction}><input type="hidden" name="payment_id" value={p.id}/><button data-feedback="Voiding payment…" className="text-xs font-semibold text-red-700">Void</button></form>}</td></tr>)}</tbody></table></div></section>
  </section>;
}
