import { inviteStaffAction } from "@/app/actions";
import { AccessDenied } from "@/components/access-denied";
import { requireAppContext } from "@/lib/app-context";
import { ROLE_GROUPS, roleAllowed } from "@/lib/roles";

export default async function StaffPage(){
  const ctx=await requireAppContext();
  if(!roleAllowed(ctx.role,ROLE_GROUPS.staffWorkspace)) return <AccessDenied area="staff administration"/>;
  const {data:staff,error}=await ctx.supabase.from("organization_members").select("id,user_id,role,location_id,is_active,profiles(full_name,phone),locations(name)").eq("organization_id",ctx.organization.id).order("created_at");
  if(error) throw new Error(error.message);
  const canInvite=roleAllowed(ctx.role,ROLE_GROUPS.staffInviters);
  return <section className="mx-auto max-w-7xl space-y-6"><div><p className="text-sm text-[#7a7f89]">People & permissions</p><h1 className="mt-1 text-3xl font-semibold tracking-tight">Staff</h1></div>{canInvite&&<section className="rounded-2xl border border-[#e4e6ea] bg-white p-5"><h2 className="font-semibold">Invite staff member</h2><p className="mt-1 text-sm text-[#7a7f89]">The invitation is sent by Supabase Auth; the secret key stays server-side.</p><form action={inviteStaffAction} className="mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-5"><input name="full_name" required placeholder="Full name" className="rounded-lg border border-[#dfe2e7] px-3 py-2"/><input name="email" type="email" required placeholder="Email" className="rounded-lg border border-[#dfe2e7] px-3 py-2"/><select name="role" defaultValue="reception" className="rounded-lg border border-[#dfe2e7] px-3 py-2"><option value="admin">Admin</option><option value="manager">Manager</option><option value="reception">Reception</option><option value="trainer">Trainer</option><option value="accountant">Accountant</option></select><select name="location_id" defaultValue={ctx.location.id} className="rounded-lg border border-[#dfe2e7] px-3 py-2">{ctx.locations.map((l:any)=><option key={l.id} value={l.id}>{l.name}</option>)}</select><button data-feedback="Sending invitation…" className="rounded-lg bg-[#111318] px-4 py-2 text-sm font-semibold text-white">Send invite</button></form></section>}<section className="rounded-2xl border border-[#e4e6ea] bg-white"><div className="overflow-x-auto"><table className="w-full min-w-[650px] text-left text-sm"><thead className="bg-[#fafafa] text-xs uppercase text-[#8a9099]"><tr><th className="px-5 py-3">Staff</th><th>Role</th><th>Location</th><th>Status</th></tr></thead><tbody>{(staff??[]).map((s:any)=><tr key={s.id} className="border-t border-[#f0f1f3]"><td className="px-5 py-4 font-medium">{s.profiles?.full_name||"Invited user"}</td><td className="capitalize">{s.role}</td><td>{s.locations?.name||"All / default"}</td><td>{s.is_active?"Active":"Disabled"}</td></tr>)}</tbody></table></div></section></section>;
}
