import { OperationKeyInput } from "@/components/operation-key-input";
import Link from "next/link";
import { createPlanAction } from "@/app/actions";
import { AccessDenied } from "@/components/access-denied";
import { requireAppContext } from "@/lib/app-context";
import { formatDate, formatMoney } from "@/lib/format";
import { ROLE_GROUPS, roleAllowed } from "@/lib/roles";

export default async function MembershipsPage() {
  const ctx=await requireAppContext();
  if(!roleAllowed(ctx.role,ROLE_GROUPS.membershipWorkspace)) return <AccessDenied area="memberships"/>;
  const canCreatePlans=roleAllowed(ctx.role,ROLE_GROUPS.planManagers);
  const [plansRes,membershipsRes]=await Promise.all([
    ctx.supabase.from("membership_plans").select("*").eq("organization_id",ctx.organization.id).order("is_active",{ascending:false}).order("name"),
    ctx.supabase.from("memberships").select("id,status,starts_on,ends_on,visits_remaining,price_minor,currency,member_id,members(first_name,last_name),membership_plans(name)").eq("organization_id",ctx.organization.id).order("created_at",{ascending:false}).limit(100),
  ]);
  if(plansRes.error) throw new Error(plansRes.error.message);
  if(membershipsRes.error) throw new Error(membershipsRes.error.message);
  return <section className="mx-auto max-w-7xl space-y-6"><div><p className="text-sm text-[#7a7f89]">Plans & renewals</p><h1 className="mt-1 text-3xl font-semibold tracking-tight">Memberships</h1></div><div className="grid gap-6 xl:grid-cols-[.8fr_1.2fr]">
    <section className="rounded-2xl border border-[#e4e6ea] bg-white p-5"><h2 className="font-semibold">{canCreatePlans?"Create membership plan":"Membership plans"}</h2>{canCreatePlans&&<form action={createPlanAction} className="mt-4 grid gap-3"><OperationKeyInput /><label className="text-sm">Plan name<input name="name" required placeholder="Monthly" className="mt-1 w-full rounded-lg border border-[#dfe2e7] px-3 py-2"/></label><div className="grid grid-cols-2 gap-3"><label className="text-sm">Type<select name="billing_type" defaultValue="one_time" className="mt-1 w-full rounded-lg border border-[#dfe2e7] px-3 py-2"><option value="one_time">Fixed duration</option><option value="visit_pack">Visit pack</option><option value="recurring">Recurring-ready</option></select></label><label className="text-sm">Currency<select name="currency" defaultValue={ctx.organization.base_currency} className="mt-1 w-full rounded-lg border border-[#dfe2e7] px-3 py-2"><option>USD</option><option>EUR</option><option>LBP</option><option>AED</option><option>SAR</option><option>CAD</option><option>GBP</option></select></label></div><div className="grid grid-cols-3 gap-3"><label className="text-sm">Price<input name="price" required inputMode="decimal" placeholder="55.00" className="mt-1 w-full rounded-lg border border-[#dfe2e7] px-3 py-2"/></label><label className="text-sm">Days<input name="duration_days" type="number" min="1" placeholder="30" className="mt-1 w-full rounded-lg border border-[#dfe2e7] px-3 py-2"/></label><label className="text-sm">Visits<input name="included_visits" type="number" min="1" placeholder="Unlimited" className="mt-1 w-full rounded-lg border border-[#dfe2e7] px-3 py-2"/></label></div><button data-feedback="Creating plan…" className="rounded-lg bg-[#111318] px-4 py-2.5 text-sm font-semibold text-white">Create plan</button></form>}<div className="mt-5 space-y-2">{(plansRes.data??[]).map((p:any)=><div key={p.id} className="rounded-xl bg-[#f7f8f9] p-3"><div className="flex items-center justify-between"><p className="text-sm font-semibold">{p.name}</p><span className="text-sm font-semibold">{formatMoney(p.price_minor,p.currency)}</span></div><p className="mt-1 text-xs text-[#7a7f89]">{p.duration_days?`${p.duration_days} days`:"No fixed expiry"}{p.included_visits?` · ${p.included_visits} visits`:" · unlimited visits"}</p></div>)}</div></section>
    <section className="rounded-2xl border border-[#e4e6ea] bg-white"><div className="border-b border-[#eceef1] p-5"><h2 className="font-semibold">Membership ledger</h2><p className="mt-1 text-sm text-[#7a7f89]">Latest active and historical memberships.</p></div><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead className="bg-[#fafafa] text-xs uppercase text-[#8a9099]"><tr><th className="px-5 py-3">Member</th><th>Plan</th><th>Start</th><th>End</th><th>Status</th><th></th></tr></thead><tbody>{(membershipsRes.data??[]).map((m:any)=><tr key={m.id} className="border-t border-[#f0f1f3]"><td className="px-5 py-4 font-medium">{m.members?.first_name} {m.members?.last_name}</td><td>{m.membership_plans?.name??"—"}</td><td>{formatDate(m.starts_on)}</td><td>{formatDate(m.ends_on)}</td><td><span className="rounded-full bg-[#f0f2f4] px-2.5 py-1 text-xs font-semibold capitalize">{m.status}</span></td><td className="pr-5 text-right"><Link href={`/members/${m.member_id}`} className="font-semibold">Open →</Link></td></tr>)}</tbody></table></div></section>
  </div></section>;
}
