-- Core multi-tenant schema for the gym SaaS starter.
-- Run through Supabase migrations. Every tenant-owned table carries organization_id.

create extension if not exists pgcrypto;

create type public.app_role as enum ('owner','admin','manager','reception','trainer','accountant');
create type public.member_status as enum ('lead','active','paused','expired','cancelled','archived');
create type public.membership_status as enum ('pending','active','paused','expired','cancelled');
create type public.payment_status as enum ('pending','paid','failed','refunded','voided');
create type public.session_status as enum ('scheduled','completed','cancelled','no_show');

create table public.organizations (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  slug text not null unique,
  country_code text not null default 'LB',
  timezone text not null default 'Asia/Beirut',
  base_currency text not null default 'USD',
  logo_path text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.locations (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  name text not null,
  address text,
  timezone text,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  unique (organization_id, name)
);

create table public.profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  full_name text,
  phone text,
  avatar_path text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.organization_members (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  role public.app_role not null,
  location_id uuid references public.locations(id) on delete set null,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  unique (organization_id, user_id)
);

create table public.members (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  home_location_id uuid references public.locations(id) on delete set null,
  member_number bigint generated by default as identity,
  first_name text not null,
  last_name text not null,
  phone text,
  email text,
  date_of_birth date,
  emergency_contact_name text,
  emergency_contact_phone text,
  photo_path text,
  status public.member_status not null default 'active',
  joined_at date not null default current_date,
  archived_at timestamptz,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (organization_id, member_number)
);

create table public.member_notes (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  member_id uuid not null references public.members(id) on delete cascade,
  note text not null,
  is_private boolean not null default true,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);

create table public.membership_plans (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  location_id uuid references public.locations(id) on delete set null,
  name text not null,
  billing_type text not null check (billing_type in ('one_time','recurring','visit_pack')),
  duration_days integer check (duration_days is null or duration_days > 0),
  included_visits integer check (included_visits is null or included_visits > 0),
  price_minor bigint not null check (price_minor >= 0),
  currency text not null default 'USD',
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.memberships (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  member_id uuid not null references public.members(id) on delete restrict,
  plan_id uuid not null references public.membership_plans(id) on delete restrict,
  location_id uuid references public.locations(id) on delete set null,
  status public.membership_status not null default 'pending',
  starts_on date not null,
  ends_on date,
  visits_remaining integer,
  auto_renew boolean not null default false,
  frozen_until date,
  price_minor bigint not null check (price_minor >= 0),
  currency text not null,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (ends_on is null or ends_on >= starts_on)
);

create table public.membership_freezes (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  membership_id uuid not null references public.memberships(id) on delete restrict,
  starts_on date not null,
  ends_on date not null,
  reason text,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  check (ends_on >= starts_on)
);

create table public.payments (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  location_id uuid references public.locations(id) on delete set null,
  member_id uuid references public.members(id) on delete restrict,
  membership_id uuid references public.memberships(id) on delete restrict,
  amount_minor bigint not null check (amount_minor >= 0),
  currency text not null,
  payment_method text not null,
  status public.payment_status not null default 'paid',
  external_reference text,
  receipt_number bigint generated by default as identity,
  note text,
  created_by uuid references auth.users(id) on delete set null,
  paid_at timestamptz not null default now(),
  voided_at timestamptz,
  created_at timestamptz not null default now(),
  unique (organization_id, receipt_number)
);

create table public.check_ins (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  location_id uuid not null references public.locations(id) on delete restrict,
  member_id uuid not null references public.members(id) on delete restrict,
  membership_id uuid references public.memberships(id) on delete set null,
  method text not null check (method in ('manual','qr','barcode','member_number','phone')),
  overridden boolean not null default false,
  override_reason text,
  checked_in_by uuid references auth.users(id) on delete set null,
  checked_in_at timestamptz not null default now()
);

create table public.pt_packages (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  member_id uuid not null references public.members(id) on delete restrict,
  trainer_user_id uuid references auth.users(id) on delete set null,
  sessions_purchased integer not null check (sessions_purchased > 0),
  sessions_remaining integer not null check (sessions_remaining >= 0),
  expires_on date,
  created_at timestamptz not null default now()
);

create table public.pt_sessions (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  location_id uuid references public.locations(id) on delete set null,
  member_id uuid not null references public.members(id) on delete restrict,
  trainer_user_id uuid not null references auth.users(id) on delete restrict,
  pt_package_id uuid references public.pt_packages(id) on delete set null,
  starts_at timestamptz not null,
  ends_at timestamptz not null,
  status public.session_status not null default 'scheduled',
  notes text,
  created_at timestamptz not null default now(),
  check (ends_at > starts_at)
);

create table public.leads (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  location_id uuid references public.locations(id) on delete set null,
  full_name text not null,
  phone text,
  email text,
  source text,
  stage text not null default 'new' check (stage in ('new','contacted','trial','negotiating','joined','lost')),
  lost_reason text,
  next_follow_up_at timestamptz,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.audit_logs (
  id bigint generated always as identity primary key,
  organization_id uuid not null references public.organizations(id) on delete cascade,
  actor_user_id uuid references auth.users(id) on delete set null,
  action text not null,
  entity_type text not null,
  entity_id text,
  before_data jsonb,
  after_data jsonb,
  created_at timestamptz not null default now()
);

create table public.saas_subscriptions (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null unique references public.organizations(id) on delete cascade,
  provider text not null default 'stripe',
  provider_customer_id text,
  provider_subscription_id text,
  plan_code text not null default 'trial',
  status text not null default 'trialing',
  trial_ends_at timestamptz,
  current_period_ends_at timestamptz,
  grace_ends_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.webhook_events (
  id uuid primary key default gen_random_uuid(),
  provider text not null,
  external_event_id text not null,
  event_type text not null,
  payload jsonb not null,
  processed_at timestamptz,
  error_message text,
  created_at timestamptz not null default now(),
  unique (provider, external_event_id)
);

-- Performance indexes for the hot paths.
create index members_org_status_idx on public.members (organization_id, status);
create index members_org_phone_idx on public.members (organization_id, phone);
create index memberships_org_status_end_idx on public.memberships (organization_id, status, ends_on);
create index payments_org_paid_at_idx on public.payments (organization_id, paid_at desc);
create index check_ins_org_time_idx on public.check_ins (organization_id, checked_in_at desc);
create index leads_org_stage_idx on public.leads (organization_id, stage);
create index audit_logs_org_time_idx on public.audit_logs (organization_id, created_at desc);

-- Security-definer helpers avoid recursive RLS policies on organization_members.
create or replace function public.is_org_member(org_id uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.organization_members om
    where om.organization_id = org_id
      and om.user_id = auth.uid()
      and om.is_active = true
  );
$$;

create or replace function public.has_org_role(org_id uuid, allowed_roles public.app_role[])
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.organization_members om
    where om.organization_id = org_id
      and om.user_id = auth.uid()
      and om.is_active = true
      and om.role = any(allowed_roles)
  );
$$;

revoke all on function public.is_org_member(uuid) from public;
revoke all on function public.has_org_role(uuid, public.app_role[]) from public;
grant execute on function public.is_org_member(uuid) to authenticated;
grant execute on function public.has_org_role(uuid, public.app_role[]) to authenticated;

-- Enable RLS everywhere exposed to the Data API.
alter table public.organizations enable row level security;
alter table public.locations enable row level security;
alter table public.profiles enable row level security;
alter table public.organization_members enable row level security;
alter table public.members enable row level security;
alter table public.member_notes enable row level security;
alter table public.membership_plans enable row level security;
alter table public.memberships enable row level security;
alter table public.membership_freezes enable row level security;
alter table public.payments enable row level security;
alter table public.check_ins enable row level security;
alter table public.pt_packages enable row level security;
alter table public.pt_sessions enable row level security;
alter table public.leads enable row level security;
alter table public.audit_logs enable row level security;
alter table public.saas_subscriptions enable row level security;
alter table public.webhook_events enable row level security;

-- Explicit Data API grants. RLS then determines which rows are visible/writable.
revoke all on table public.organizations, public.locations, public.profiles, public.organization_members, public.members, public.member_notes, public.membership_plans, public.memberships, public.membership_freezes, public.payments, public.check_ins, public.pt_packages, public.pt_sessions, public.leads, public.audit_logs, public.saas_subscriptions, public.webhook_events from anon;
revoke all on table public.organizations, public.locations, public.profiles, public.organization_members, public.members, public.member_notes, public.membership_plans, public.memberships, public.membership_freezes, public.payments, public.check_ins, public.pt_packages, public.pt_sessions, public.leads, public.audit_logs, public.saas_subscriptions, public.webhook_events from authenticated;

grant select, update on public.organizations to authenticated;
grant select, insert, update on public.locations to authenticated;
grant select, insert, update on public.profiles to authenticated;
grant select, insert, update, delete on public.organization_members to authenticated;
grant select, insert, update on public.members to authenticated;
grant select, insert, update, delete on public.member_notes to authenticated;
grant select, insert, update on public.membership_plans to authenticated;
grant select, insert, update on public.memberships to authenticated;
grant select, insert, update, delete on public.membership_freezes to authenticated;
grant select, insert, update on public.payments to authenticated;
grant select, insert on public.check_ins to authenticated;
grant select, insert, update on public.pt_packages to authenticated;
grant select, insert, update on public.pt_sessions to authenticated;
grant select, insert, update on public.leads to authenticated;
grant select, insert on public.audit_logs to authenticated;
grant select on public.saas_subscriptions to authenticated;
-- webhook_events intentionally receives no anon/authenticated grants.

-- Profiles: a user may read/update only their own profile.
create policy profiles_select_self on public.profiles for select to authenticated using (user_id = auth.uid());
create policy profiles_insert_self on public.profiles for insert to authenticated with check (user_id = auth.uid());
create policy profiles_update_self on public.profiles for update to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());

-- Organization and membership visibility.
create policy organizations_select_member on public.organizations for select to authenticated using (public.is_org_member(id));
create policy locations_select_member on public.locations for select to authenticated using (public.is_org_member(organization_id));
create policy organizations_update_admin on public.organizations for update to authenticated
  using (public.has_org_role(id, array['owner','admin']::public.app_role[]))
  with check (public.has_org_role(id, array['owner','admin']::public.app_role[]));
create policy locations_insert_admin on public.locations for insert to authenticated
  with check (public.has_org_role(organization_id, array['owner','admin']::public.app_role[]));
create policy locations_update_admin on public.locations for update to authenticated
  using (public.has_org_role(organization_id, array['owner','admin']::public.app_role[]))
  with check (public.has_org_role(organization_id, array['owner','admin']::public.app_role[]));
create policy organization_members_select on public.organization_members for select to authenticated
  using (user_id = auth.uid() or public.has_org_role(organization_id, array['owner','admin','manager']::public.app_role[]));
create policy organization_members_manage on public.organization_members for all to authenticated
  using (public.has_org_role(organization_id, array['owner','admin']::public.app_role[]))
  with check (public.has_org_role(organization_id, array['owner','admin']::public.app_role[]));

-- Tenant read/write policies. Role-specific business rules can become more granular per module.
create policy members_select on public.members for select to authenticated using (public.is_org_member(organization_id));
create policy members_insert on public.members for insert to authenticated
  with check (public.has_org_role(organization_id, array['owner','admin','manager','reception']::public.app_role[]));
create policy members_update on public.members for update to authenticated
  using (public.has_org_role(organization_id, array['owner','admin','manager','reception']::public.app_role[]))
  with check (public.has_org_role(organization_id, array['owner','admin','manager','reception']::public.app_role[]));
-- No normal DELETE policy: members with history are archived instead.

create policy member_notes_select on public.member_notes for select to authenticated using (public.is_org_member(organization_id));
create policy member_notes_write on public.member_notes for all to authenticated
  using (public.is_org_member(organization_id)) with check (public.is_org_member(organization_id));

create policy plans_select on public.membership_plans for select to authenticated using (public.is_org_member(organization_id));
create policy plans_insert on public.membership_plans for insert to authenticated
  with check (public.has_org_role(organization_id, array['owner','admin','manager']::public.app_role[]));
create policy plans_update on public.membership_plans for update to authenticated
  using (public.has_org_role(organization_id, array['owner','admin','manager']::public.app_role[]))
  with check (public.has_org_role(organization_id, array['owner','admin','manager']::public.app_role[]));

create policy memberships_select on public.memberships for select to authenticated using (public.is_org_member(organization_id));
create policy memberships_insert on public.memberships for insert to authenticated
  with check (public.has_org_role(organization_id, array['owner','admin','manager','reception']::public.app_role[]));
create policy memberships_update on public.memberships for update to authenticated
  using (public.has_org_role(organization_id, array['owner','admin','manager','reception']::public.app_role[]))
  with check (public.has_org_role(organization_id, array['owner','admin','manager','reception']::public.app_role[]));

create policy freezes_select on public.membership_freezes for select to authenticated using (public.is_org_member(organization_id));
create policy freezes_write on public.membership_freezes for all to authenticated
  using (public.has_org_role(organization_id, array['owner','admin','manager','reception']::public.app_role[]))
  with check (public.has_org_role(organization_id, array['owner','admin','manager','reception']::public.app_role[]));

create policy payments_select on public.payments for select to authenticated
  using (public.has_org_role(organization_id, array['owner','admin','manager','reception','accountant']::public.app_role[]));
create policy payments_insert on public.payments for insert to authenticated
  with check (public.has_org_role(organization_id, array['owner','admin','manager','reception','accountant']::public.app_role[]));
create policy payments_update on public.payments for update to authenticated
  using (public.has_org_role(organization_id, array['owner','admin','manager','accountant']::public.app_role[]))
  with check (public.has_org_role(organization_id, array['owner','admin','manager','accountant']::public.app_role[]));
-- No client DELETE policy for payments: void/refund, never destructive deletion.

create policy checkins_select on public.check_ins for select to authenticated using (public.is_org_member(organization_id));
create policy checkins_insert on public.check_ins for insert to authenticated with check (public.is_org_member(organization_id));

create policy pt_packages_select on public.pt_packages for select to authenticated using (public.is_org_member(organization_id));
create policy pt_packages_write on public.pt_packages for all to authenticated
  using (public.is_org_member(organization_id)) with check (public.is_org_member(organization_id));
create policy pt_sessions_select on public.pt_sessions for select to authenticated using (public.is_org_member(organization_id));
create policy pt_sessions_write on public.pt_sessions for all to authenticated
  using (public.is_org_member(organization_id)) with check (public.is_org_member(organization_id));

create policy leads_select on public.leads for select to authenticated using (public.is_org_member(organization_id));
create policy leads_write on public.leads for all to authenticated
  using (public.has_org_role(organization_id, array['owner','admin','manager','reception']::public.app_role[]))
  with check (public.has_org_role(organization_id, array['owner','admin','manager','reception']::public.app_role[]));

create policy audit_select on public.audit_logs for select to authenticated
  using (public.has_org_role(organization_id, array['owner','admin','manager']::public.app_role[]));
create policy audit_insert on public.audit_logs for insert to authenticated with check (public.is_org_member(organization_id));
-- Audit records are intentionally immutable to normal users.

create policy subscription_select on public.saas_subscriptions for select to authenticated
  using (public.has_org_role(organization_id, array['owner','admin']::public.app_role[]));
-- subscription/webhook writes must be server-side with a secret/service credential.

-- webhook_events deliberately has no authenticated policies.
